### ISSUE TITLE
New Animation

### ISSUE THREAD

**Issue by jasimrazi** [GauravMKedia/animation-collections#11]
Add new loading animation

**Comment by GauravMKedia** [comment]
What do you mean to do?

**Comment by GauravMKedia** [comment]
> Add new loading animation

What do you mean to do ?

**Comment by jasimrazi** [comment]
I'm thinking of adding a new loading animation to the animation collections.

**Comment by GauravMKedia** [comment]
> I would love to do that , can you please assign it to me

Okay, you can work on it and then just make a pull request.
