### ISSUE TITLE
Add new attractive animations

### ISSUE THREAD

**Issue by Simranjain06** [GauravMKedia/animation-collections#23]
I want to add new attractive animations using HTML,CSS and JS.

**Comment by Simranjain06** [comment]
Hey, I am interested in working on this task .can you assign me this task?

**Comment by GauravMKedia** [comment]
> Hey, I am interested in working on this task .can you assign me this task?

Okay, you can work just make sure you add then animation gif and update data.js file.

**Comment by Simranjain06** [comment]
Ok, can you assign me this issue
