### ISSUE TITLE
Add "back-to-top" button

### ISSUE THREAD

**Issue by AdithiDesai** [GauravMKedia/animation-collections#40]

**Comment by AdithiDesai** [comment]
I would like to add this button to your website. Can you assign this task to me?

**Comment by GauravMKedia** [comment]
> I would like to add this button to your website. Can you assign this task to me? @GauravMKedia

Which Button is it some kind of button animation or something else?

**Comment by AdithiDesai** [comment]
No. Its basically a button which takes us to the top of the page. It is located at the end of the page. 
![Uploading Top-2-.png…]()

**Comment by GauravMKedia** [comment]
Okay!!
You can add.
