### ISSUE TITLE
I want to add a new animation "circle-wave"

### ISSUE THREAD

**Issue by gunalirezqimauludi** [GauravMKedia/animation-collections#54]
I want to take part in contributing to the "**Hacktoberfest 2022**" event. The contribution I want to make is to add a loading animation like the following link [cirlce-wave](https://i.imgur.com/kubJGo7.gifl)

**Comment by GauravMKedia** [comment]
Okay!!

**Comment by GauravMKedia** [comment]
> I want to take part in contributing to the "**Hacktoberfest 2022**" event. The contribution I want to make is to add a loading animation like the following link [cirlce-wave](https://i.imgur.com/kubJGo7.gifl)

Okay!!
