### ISSUE TITLE
Image fetching from imgur site

### ISSUE THREAD

**Issue by GauravMKedia** [GauravMKedia/animation-collections#6]
I want to keep my repository size smaller so for that I intend to use **Imgur** open source site where user will make their account and add the gif link of animation which they are adding in data.js file so that it will be seen in animation website page of this repository.

**Comment by dilshad360** [comment]
I would like to work on this issue

**Comment by GauravMKedia** [comment]
Okay!!
You can work, just make sure that the gif are loading properly.
