### ISSUE TITLE
Making Animation website awesome using CSS

### ISSUE THREAD

**Issue by GauravMKedia** [GauravMKedia/animation-collections#7]
I have created a basic website for displaying the animation added by user in one place along with user detail.
I want you to make the website more responsive and attractive.

**Comment by abitsalihu** [comment]
Hey @GauravMKedia, I would like to work on this issue. :)

**Comment by GauravMKedia** [comment]
> Hey @GauravMKedia, I would like to work on this issue. :)

Okay!!
You can work.
