### ISSUE TITLE
Adding loading animations

### ISSUE THREAD

**Issue by AdithiDesai** [GauravMKedia/animation-collections#77]

**Comment by AdithiDesai** [comment]
I want to add loading animations to your website. Can you please assign it to me?

**Comment by Manishgupta200** [comment]
Assign it to me. I would like to do on that issue

**Comment by Manishgupta200** [comment]
@GauravMKedia please look at my pull request. I solved this issue. If it is ok then accept it under Hacktoberfest2022. Thankyou
