### ISSUE TITLE
hello sir i would like to to contribute but don't know how to convert my code for animation into gif please help

### ISSUE THREAD

**Issue by AmanTiwari19** [GauravMKedia/animation-collections#97]

**Comment by GauravMKedia** [comment]
> _No description provided._

All the step and link, I have mentioned in  Readme file, how to create gif section.
You just have to run your animation using any compiler then screen record for few second, upload that video to any video to gif convertor and crop and cut the video as needed and download the gif. Then Upload the gif at imgur site and get the gif link.
